[package]
name = "site"
version = "0.1.0"
authors = ["Christopher Moran <christopher.and.moran@gmail.com>"]
edition = "2018"
license = "AGPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
markdown = "0.3"